require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - app/mailers/application_mailer.rb
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/assets.rb
    - config/puma.rb
    - config/initializers/**/*
    - db/migrate/**/*
    - test/**/*

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - app/mailers/application_mailer.rb
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/assets.rb
    - config/puma.rb
    - config/initializers/**/*
    - test/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Style/SymbolArray:
  Exclude:
    - config/initializers/**/*
