development:
  adapter: postgresql
  encoding: unicode
  database: blackjack_development
  pool: 5
  host: localhost
  username: blackjack
  password: <%= ENV['BLACKJACK_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: blackjack_test
  pool: 5
  username: blackjack
  password: blackjack

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
